//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> ImportId { get; set; }
        public Nullable<int> BookId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Iep_Id { get; set; }
        public string Type { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual InventoryImport InventoryImport { get; set; }
        public virtual InventoryExport InventoryExport { get; set; }
    }
}
