//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryExport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryExport()
        {
            this.InventoryDetail = new HashSet<InventoryDetail>();
        }
    
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Export_Date { get; set; }
        public int Iep_Id { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDetail> InventoryDetail { get; set; }
        public virtual Users Users { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
