//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItem_Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<double> BookPrice { get; set; }
        public Nullable<int> BookQuantity { get; set; }
        public string CustomerPhone { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
